### ISSUE TITLE
Use of Rx - use unicode

### ISSUE THREAD

**Issue by ps2270** [cu-mkp/m-k-manuscript-data#940]
In the first half of the ms., THU and TT used R{ecipe} to render Rx. CAG and PHS used unicode Rx. @thuchacz @TillmannTaape  please search for this and use the unicode in all three versions.

**Comment by ps2270** [comment]
I've found so far on 50r, but that's just serendipity--haven't been looking

**Comment by Pantagrueliste** [comment]
43r, 48v, 50r.

**Comment by Pantagrueliste** [comment]
note that in 48v I changed:
> <ab>Take one <ms>lb</ms> of <m>antimony</m>, <ms>half a lb</ms> <m>black soap</m>, and <ms>half a lb</ms> of <m>tartar from <pl>Montpellier</pl></m>.

to

> <ab>℞ one <ms>lb</ms> of <m>antimony</m>, <ms>half a lb</ms> <m>black soap</m>, and <ms>half a lb</ms> of <m>tartar from <pl>Montpellier</pl></m>.

**Comment by Pantagrueliste** [comment]
idem in 50r:
> <ab>Take a <tl><m>glass</m> ampul</tl> with an opening capable of
receiving <pa>cherries</pa>

to 

><ab>℞ a <tl><m>glass</m> ampul</tl> with an opening capable of
receiving <pa>cherries</pa>

**Comment by Pantagrueliste** [comment]
done

**Comment by ps2270** [comment]
@Pantagrueliste I happened to look at one of these folios, and this correction of inserting unicode for Rx is not implemented in any of the 3 folios you referenced.  Before you close an issue, could you please check that it was implemented.  Can you please try again on all **3** of these folios in all **3 versions**?

**Comment by Pantagrueliste** [comment]
This is strange, it appears that the changes I have committed six days ago never merged.

**Comment by ps2270** [comment]
@Pantagrueliste  Sorry to say this, **but 48v is still not showing Rx**.  43r and 50v are fine now.

**Comment by Pantagrueliste** [comment]
It appears on my files and on the staging edition: perhaps your browser's cache needs to be refreshed...

**Comment by ps2270** [comment]
Ok
